services:

  postgres:
    image: postgres:14
    container_name: postgres-hl7
    restart: unless-stopped
    environment:
      POSTGRES_USER: hl7user
      POSTGRES_PASSWORD: hl7pass
      POSTGRES_DB: hl7db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hl7net

  mirth:
    image: nextgenhealthcare/connect:4.4.1
    container_name: mirth
    restart: unless-stopped
    ports:
      - "8080:8080"   # HTTP admin
      - "8443:8443"   # HTTPS admin (necesario para el JNLP)
      - "6661:6661"   # HL7 listener
    environment:
      DATABASE: postgres
      DATABASE_URL: jdbc:postgresql://postgres-hl7:5432/hl7db
      DATABASE_USERNAME: hl7user
      DATABASE_PASSWORD: hl7pass
      DATABASE_MAXCONNECTIONS: 20
      JAVA_OPTS: "-Xms512m -Xmx1024m"
    volumes:
      - mirth_data:/opt/connect/appdata
    depends_on:
      - postgres
    networks:
      - hl7net

  hapi:
    image: hapiproject/hapi:latest
    container_name: hapi-fhir
    restart: unless-stopped
    ports:
      - "8081:8080"   # FHIR API
    networks:
      - hl7net

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - hl7net

volumes:
  postgres_data:
  mirth_data:
  portainer_data:

networks:
  hl7net:
